spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movenest_api?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Hungyeuy@2410  # Nếu không có giá trị, dùng giá trị mặc định
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

jwt:
  secret: QQU0Alvur6b2dBvD5pcC4C3mlRgSm9OUTfrGJMFtFlU=
  expiration: 360000000  # 10 hours in milliseconds
expiration: 2592000000
logging:
  level:
    org:
      springframework:
        security: DEBUG

