version: "3.8"

services:
  backend:
    build: ./movienest_api
    image: movienest-api
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/moviedb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - JWT_SECRET=QQU0Alvur6b2dBvD5pcC4C3mlRgSm9OUTfrGJMFtFlU=
      - JWT_EXPIRATION=360000000
    depends_on:
      - mysql
    networks:
      - movienest_network

  frontend:
    build: ./movienest_app
    image: movienest-app
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=/api # URL tương đối
    depends_on:
      - backend
    networks:
      - movienest_network

  mysql:
    image: mysql:8
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moviedb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - movienest_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Expose ra port 80 của VPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - movienest_network

volumes:
  mysql_data:
    driver: local

networks:
  movienest_network:
    driver: bridge
